name: Build ESP32

on: [push, pull_request]

jobs:
  build-esp32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli compile --fqbn esp32:esp32:dev firmware/esp32
